server:
  port: 8082
spring:
  application:
    name: springboot-liteflow #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/x_file_storage?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=UTC
    username: root
    password: xxl666
liteflow:
  rule-source: config/flow.el.xml
