server:
  port: 8082
spring:
  application:
    name: springboot-liteflow #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/x_file_storage?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=UTC
    username: root
    password: xxl666
liteflow:
  #  rule-source: config/flow.el.xml
  rule-source-ext-data-map:
    #数据源基础配置，项目中配置过spring.datasource无需再次配置
    #    url: jdbc:mysql://127.0.0.1:3306/x_file_storage
    #    driverClassName: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: xxl666
    applicationName: liteflowdemo
    #配置流程的表名
    chainTableName: LITE_FLOW_CHAIN
    #注意，下面xxxField结尾的，都是表中的列名
    #应用名
    chainApplicationNameField: application_name
    #流程名
    chainNameField: chain_name
    #流程表达式
    elDataField: el_data
    pollingEnabled: true
    ##以下非必须，默认1分钟
    pollingIntervalSeconds: 60
    pollingStartSeconds: 60