
###
POST http://localhost/api/user/getUserInfoByPhone

### JasyptController get接口
GET http://localhost:8080/get

### JasyptController jasypt接口
GET http://localhost:8080/jasypt

### 单个保存
POST {{springboot_jasypt_host}}/savePerson
Content-Type: application/json

{
  "phoneNumber": "15510008021",
  "userName": "海豹"
}

### 条件查询
POST {{springboot_jasypt_host}}/findPerson
Content-Type: application/json

{
  "phoneNumber": "1551"
}

### 获取列表信息
GET http://localhost:8080/list

### 根据id查询
GET http://localhost:8080/get/1664208306383753216
