server:
  port: 9001
spring:
  application:
    name: springboot-mybatis-plus #指定服务名
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/excel_poi?characterEncoding=utf-8
#    username: root
#    password: xxl666
#    url: jdbc:mysql://192.168.1.109:3306/ekclinic_user?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    username: root
#    password: ek070901

# Mybatis-Plus 配置
mybatis-plus:
  # mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.entity
  global-config:
    id-type: 0 #0:数据库ID自增 1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用