# ???
spring:
  # ?????
  datasource:
    # ??????druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #?????mysql-connector-java??
    # druid??
    druid:
      # ????
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # ????????????
        url: jdbc:mysql://127.0.0.1:3306/multi_tenant_master?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: xxl666
      # ??db??
      db1:
        driver-class-name: com.mysql.cj.jdbc.Driver #?????mysql-connector-java??
        url: jdbc:mysql://127.0.0.1:3306/multi_tenant_db1?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: xxl666
      initial-size: 5 # ?????????????
      max-active: 30 # ???????
      min-idle: 5 # ???????
      max-wait: 60000 # ????????????????
      time-between-eviction-runs-millis: 60000 # ???????????????????????????????
      min-evictable-idle-time-millis: 300000 # ????????????????
      validation-query: SELECT 1 FROM DUAL # ???????????sql??????????
      test-while-idle: true # ?????true?????????????????????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
      test-on-borrow: false # ???????validationQuery?????????????????????
      test-on-return: false # ???????validationQuery?????????????????????
      pool-prepared-statements: true # ????preparedStatement????PSCache?PSCache???????????????????oracle??mysql??????
      max-pool-prepared-statement-per-connection-size: 50 # ???PSCache???????0????0??poolPreparedStatements???????true?
      filters: stat,wall,log4j2 # ?????????filters????????sql??????????????filters?stat:?????log4j??????wall???sql??
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 # ??connectProperties?????mergeSql????SQL??
      use-global-data-source-stat: true # ????DruidDataSource?????
      stat-view-servlet:
        allow: '' # IP???(????????????????) allow: 127.0.0.1,192.168.163.1
        deny: '' # IP??? (??????deny???allow)
        login-password: xxxxxx # ????
        login-username: admin # ???
        reset-enable: false #  ??HTML?????Reset All???
        url-pattern: /druid/* # ??DruidStatViewServlet
      web-stat-filter: # ??DruidStatFilter
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*