server:
  port: 9001
spring:
  application:
    name: springboot-oauth2 #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: xxl666