spring:
  redis:
    #连接url
    host: 192.168.100.105
#    host: 192.168.100.108
    #端口号
    port: 6379
    #密码
    password: root0903
#    password: ek070901
    #默认库
    database: 0
    #超时时间
    timeout: 2000
    lettuce:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 100
        min-idle: 0