spring:
  datasource:
    druid:
      mysql:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/multi_tenant_master?useUnicode=true&characterEncoding=utf-8
        username: root
        password: xxl666
      oracle:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/multi_tenant_slave?useUnicode=true&characterEncoding=utf-8
        username: root
        password: xxl666