server:
  port: 8080
spring:
  application:
    name: caffeine-service
  datasource:
    url: jdbc:mysql://192.168.233.130:3306/springboot_chowder?useSSL=false
    username: root
    password: xxl666
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 192.168.150.101
mybatis-plus:
  type-aliases-package: com.xxl.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.heima: debug
  pattern:
    dateformat: HH:mm:ss:SSS
canal:
  destination: canal
  server: 127.0.0.1:11111